### Dataset 
[Copernicus CEMS Fire Historical Dataset](https://ewds.climate.copernicus.eu/datasets/cems-fire-historical-v1?tab=overview)
### Coordinates Feature

| Column Name | Type | Description | Range in your file |
| :--- | :--- | :--- | :--- |
| `valid_time` | `datetime64[ns]` | Daily observation timestamp (459 days total: 153 days/year for May–Sept) | `2018-05-01` to `2023-09-30` |
| `latitude` | `float64` | Grid latitude at 0.25° resolution (51 grid steps) | 48.0° N to 60.5° N |
| `longitude` | `float64` | Grid longitude at 0.25° resolution (103 grid steps, in 0–360° format where 220.5° = -139.5° W and 246.0° = -114.0° W) | 220.5° E to 246.0° E (-139.5° W to -114.0° W) |
| `surface` | `float64` | Constant GRIB surface level indicator (0.0) | `0.0` |

### Fire Weather Index Features (7 Data Variables)
| NetCDF Variable (`shortName`) | Type | Full Name & What It Measures | Possible Values / Danger Class Thresholds (Canadian / EFFIS Standard) |
| :--- | :--- | :--- | :--- |
| `ffmcode` | `float64` | **Fine Fuel Moisture Code:** Moisture content of surface litter and cured fine fuels (top 1–2 cm); indicates ease of ignition and flammability. | **Continuous (0–101 scale)**<br>• Low: 0–80<br>• Moderate: 81–85<br>• High: 86–88<br>• Very High: 89–91<br>• Extreme: 92+ |
| `dufmcode` | `float64` | **Duff Moisture Code:** Moisture content of loosely compacted organic layers of moderate depth (5–10 cm); indicates fuel consumption in medium-sized woody material. | **Continuous (0 to open-ended, typically < 300)**<br>• Low: 0–15<br>• Moderate: 16–30<br>• High: 31–50<br>• Very High: 51–75<br>• Extreme: 75+ |
| `drtcode` | `float64` | **Drought Code:** Moisture content of deep, compact organic layers (10–20 cm); tracks seasonal drought effects on heavy forest fuels and smoldering potential. | **Continuous (0 to open-ended, typically < 1000)**<br>• Low: 0–100<br>• Moderate: 101–250<br>• High: 251–350<br>• Very High: 351–500<br>• Extreme: 500+ |
| `infsinx` | `float64` | **Initial Spread Index:** Combines wind speed and FFMC to estimate the expected rate of fire spread without the influence of variable fuel quantities. | **Continuous (0 to open-ended, typically < 50)**<br>• Low: 0–2<br>• Moderate: 3–5<br>• High: 6–10<br>• Very High: 11–16<br>• Extreme: 16+ |
| `fbupinx` | `float64` | **Buildup Index:** Combines DMC and DC to indicate the total amount of fuel available for combustion. | **Continuous (0 to open-ended, typically < 300)**<br>• Low: 0–20<br>• Moderate: 21–40<br>• High: 41–60<br>• Very High: 61–90<br>• Extreme: 90+ |
| `fwinx` | `float64` | **Forest Fire Weather Index:** Combines ISI and BUI into a single numerical rating of overall frontal fire intensity (general fire danger). | **Continuous (0 to open-ended, typically < 100)**<br>• Very Low: < 5.2<br>• Low: 5.2–11.2<br>• Moderate: 11.2–21.3<br>• High: 21.3–38.0<br>• Very High: 38.0–50.0<br>• Extreme: ≥ 50.0 |
| `fdsrte` | `float64` | **Fire Daily Severity Rating:** A power transformation of FWI reflecting the difficulty of controlling fires across extreme values. | **Continuous (0 to open-ended, DSR = 0.0272 × FWI^1.77)**<br>• Low: < 1<br>• Moderate: 1–3<br>• High: 3–7<br>• Very High: 7–15<br>• Extreme: 15+ |

In [ ]:
import pandas as pd

# 1. Open the CSV file with pandas
df = pd.read_csv("dataset_CEMS_18_23.csv")

# Convert valid_time to datetime
df['valid_time'] = pd.to_datetime(df['valid_time'])

# 2. Check the combined results
print(f"Total Rows:    {df.shape[0]:,}")
print(f"Total Columns: {df.shape[1]}")
print(f"Date Range:    {df['valid_time'].min().date()} to {df['valid_time'].max().date()}")

# 3. Rows by Year
df['year'] = df['valid_time'].dt.year
print("\nRows by Year:")
print(df['year'].value_counts().sort_index())

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

In [13]:
# 1. Count null (NaN) values per column and calculate the percentage
null_counts = df.isnull().sum()
null_percentages = (df.isnull().sum() / len(df)) * 100

null_summary = pd.DataFrame({
    'Null Count': null_counts,
    'Percentage (%)': null_percentages.round(2)
})

print("=== Null (Missing) Values per Column ===")
display(null_summary)

=== Null (Missing) Values per Column ===

            Null Count  Percentage (%)
valid_time           0            0.00
latitude             0            0.00
longitude            0            0.00
fbupinx        1204416           24.98
drtcode        1204416           24.98
dufmcode       1204416           24.98
ffmcode        1204416           24.98
fdsrte         1204416           24.98
fwinx          1204416           24.98
infsinx        1204416           24.98
surface              0            0.00
year                 0            0.00

In [12]:
# 2. Count zero values (col == 0) per column and calculate the percentage
zero_counts = (df == 0).sum()
zero_percentages = ((df == 0).sum() / len(df)) * 100

zero_summary = pd.DataFrame({
    'Zero Count': zero_counts,
    'Percentage (%)': zero_percentages.round(2)
})

print("=== Exact Zero (0) Values per Column ===")
display(zero_summary)

=== Exact Zero (0) Values per Column ===

            Zero Count  Percentage (%)
valid_time           0            0.00
latitude             0            0.00
longitude            0            0.00
fbupinx          22495            0.47
drtcode              0            0.00
dufmcode         37218            0.77
ffmcode              0            0.00
fdsrte               0            0.00
fwinx                0            0.00
infsinx              0            0.00
surface        4822254          100.00
year                 0            0.00